#!/bin/sh

export MYSQL_PIDFILE="/tmp/pids/mysql.pid"
export MYSQL_SOCKET="/tmp/sockets/mysql.sock"
export PENTAHO_PASSWORD_FILE="$SNAP_DATA/mysql/pentaho_password"

mkdir -p -m 750 "$(dirname $MYSQL_PIDFILE)"
mkdir -p -m 750 "$(dirname $MYSQL_SOCKET)"

mysql_is_running()
{
	[ -f "$MYSQL_PIDFILE" -a -S "$MYSQL_SOCKET" ]
}

wait_for_mysql()
{
	if ! mysql_is_running; then
		echo -n "Waiting for MySQL... "
		while ! mysql_is_running; do
			sleep 1
		done
		echo "done"
	fi
}

mysql_pid()
{
	if mysql_is_running; then
		cat "$MYSQL_PIDFILE"
	else
		echo "Unable to get MySQL PID as it's not yet running" >&2
		echo ""
	fi
}

mysql_set_pentaho_password()
{
	echo "$1" > "$PENTAHO_PASSWORD_FILE"
	chmod 600 "$PENTAHO_PASSWORD_FILE"
}

mysql_get_pentaho_password()
{
	if [ -f "$PENTAHO_PASSWORD_FILE" ]; then
		cat "$PENTAHO_PASSWORD_FILE"
	else
		echo "MySQL Pentaho password has not yet been generated" >&2
		echo ""
	fi
}

mysql_set_quartz_password()
{
   

}

mysql_set_hibernate_password()
{
	echo -n "Setting hibernate password"
	password = mysql_get_pentaho_password
    sed -i "s/{placeholder}/$password/g" $SNAP_DATA/pentaho-solutions/system/hibernate/mysql5.hibernate.cfg.xml
}


mysql_set_audit_log()
{


}

mysql_set_jackrabbit_password()
{
	echo -n "Setting jcr password"
	password = mysql_get_pentaho_password
	sed -i "s/{placeholder}/$password/g" $SNAP_DATA/pentaho-solutions/systems/jackrabbit/repository.xml
}

mysql_set_context()
{
	echo -n "Setting context password"
	password = mysql_get_pentaho_password
	sed -i "s/{placeholder}/$password/g" $SNAP_DATA/webapps/pentaho/META-INF/context.xml
}