#!/bin/sh

export MYSQL_PIDFILE="/tmp/pids/mysql.pid"
export MYSQL_SOCKET="/tmp/sockets/mysql.sock"
export PENTAHO_PASSWORD_FILE="$SNAP_DATA/mysql/pentaho_password"

mkdir -p -m 750 "$(dirname $MYSQL_PIDFILE)"
mkdir -p -m 750 "$(dirname $MYSQL_SOCKET)"

mysql_is_running()
{
	[ -f "$MYSQL_PIDFILE" -a -S "$MYSQL_SOCKET" ]
}

wait_for_mysql()
{
	if ! mysql_is_running; then
		echo -n "Waiting for MySQL... "
		while ! mysql_is_running; do
			sleep 1
		done
		echo "done"
	fi
}

mysql_pid()
{
	if mysql_is_running; then
		cat "$MYSQL_PIDFILE"
	else
		echo "Unable to get MySQL PID as it's not yet running" >&2
		echo ""
	fi
}

mysql_set_pentaho_password()
{
	echo "$1" > "$PENTAHO_PASSWORD_FILE"
	chmod 600 "$PENTAHO_PASSWORD_FILE"
}

mysql_get_pentaho_password()
{
	if [ -f "$PENTAHO_PASSWORD_FILE" ]; then
		cat "$PENTAHO_PASSWORD_FILE"
	else
		echo "MySQL Pentaho password has not yet been generated" >&2
		echo ""
	fi
}
