name: pentaho-biserver-spicule
version: '8.0'
summary: Pentaho BI Server Community Edition
description: |
     BI Server by Pentaho for data visualisation and analysis.

grade: devel
confinement: devmode

apps:
      pentaho:
        command: tomcat-launch
        daemon: simple
        plugs: [network,network-bind]
      
      mysql:
       command: bin/start_mysql
       stop-command: support-files/mysql.server stop
       daemon: simple
       restart-condition: always
       plugs: [network, network-bind]

  # MySQL client
      mysql-client:
        command: bin/mysql --defaults-file=$SNAP_DATA/mysql/root.ini
        plugs: [network, network-bind]

      mysqldump:
        command: bin/mysqldump --defaults-file=$SNAP_DATA/mysql/root.ini --lock-tables nextcloud
        plugs: [network, network-bind]
parts:
      pentaho:
          plugin: x_maven
          source: https://github.com/pentaho/pentaho-platform.git
          source-type: git
          #source-branch: 8.0.0.0
          source-branch: master
          maven-options: [-DskipTests -Dcheckstyle.skip]
          install: |
              mkdir -p $SNAPCRAFT_PART_INSTALL/webapps/pentaho
              unzip $SNAPCRAFT_PART_INSTALL/zip/pentaho-server-manual-ce-8.0-SNAPSHOT.zip -d $SNAPCRAFT_PART_INSTALL
              rm -rf $SNAPCRAFT_PART_INSTALL/zip/pentaho-server-manual-ce-8.0-SNAPSHOT.zip
              unzip $SNAPCRAFT_PART_INSTALL/pentaho.war -d $SNAPCRAFT_PART_INSTALL/webapps/pentaho
              #rm -rf SNAPCRAFT_PART_INSTALL/pentaho.war
              cp $SNAPCRAFT_PART_INSTALL/pentaho-style.war $SNAPCRAFT_PART_INSTALL/webapps/
              unzip $SNAPCRAFT_PART_INSTALL/pentaho-solutions.zip -d $SNAPCRAFT_PART_INSTALL
              rm -rf $SNAPCRAFT_PART_INSTALL/pentaho-solutions.zip
              unzip $SNAPCRAFT_PART_INSTALL/pentaho-data.zip -d $SNAPCRAFT_PART_INSTALL
              rm -rf $SNAPCRAFT_PART_INSTALL/pentaho-data.zip
          stage:
              - -pentaho-solutions/system/jackrabbit/repository.xml
              - -webapps/pentaho/META-INF/context.xml
              - -pentaho-solutions/system/hibernate/hibernate-settings.xml
              - -pentaho-solutions/system/hibernate/mysql5.hibernate.cfg.xml
              - -pentaho-solutions/system/quartz/quartz.properties
          after: [tomcat]

      tomcat:
        plugin: ant
        source: http://svn.apache.org/repos/asf/tomcat/tc8.5.x/trunk/
        source-type: svn
        prepare: |
          cp build.properties.default build.properties
        install: |
          cp -r output/build/* $SNAPCRAFT_PART_INSTALL
          cat <<EOF > $SNAPCRAFT_PART_INSTALL/tomcat-launch
          #!/bin/sh
          cp -rn \${SNAP}/pentaho-solutions \${SNAP_DATA}/pentaho-solutions
          export JRE_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
          export JAVA_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
          export CATALINA_HOME=\${SNAP}
          export CATALINA_BASE=\${SNAP_DATA}
          export CATALINA_TMPDIR=/tmp
          cp -rn \${CATALINA_HOME}/conf \${CATALINA_BASE}/
          cp -rn \${CATALINA_HOME}/webapps \${CATALINA_BASE}/
          exec \${CATALINA_HOME}/bin/catalina.sh run
          EOF
          chmod +x $SNAPCRAFT_PART_INSTALL/tomcat-launch

      boost:
        plugin: copy
        source: https://github.com/kyrofa/boost_tarball/raw/master/boost_1_59_0.tar.gz
        source-checksum: sha1/5123209db194d66d69a9cfa5af8ff473d5941d97
        files:
          '*': boost/
        prime:
          - -*
      mysql:
        plugin: cmake
        source: https://github.com/kyrofa/mysql-server.git
        source-type: git
        source-branch: mysql-5.7.18_support_no_setpriority
        after: [boost]
        configflags:
          - -DWITH_BOOST=$SNAPCRAFT_STAGE/boost
          - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
          - -DCMAKE_INSTALL_PREFIX=/
          - -DBUILD_CONFIG=mysql_release
          - -DWITH_UNIT_TESTS=OFF
          - -DWITH_EMBEDDED_SERVER=OFF
          - -DWITH_EMBEDDED_SHARED_LIBRARY=OFF
          - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
          - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
          - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
          - -DWITH_PARTITION_STORAGE_ENGINE=OFF
          - -DINSTALL_MYSQLTESTDIR=
        build-packages:
          - wget
          - g++
          - cmake
          - bison
          - libncurses5-dev
          - libaio-dev
        stage:
          # Remove scripts that we'll be replacing with our own
          - -support-files/mysql.server
        prime:
          # Remove scripts that we'll be replacing with our own
          - -support-files/mysql.server

          # Remove unused binaries that waste space
          - -bin/innochecksum
          - -bin/lz4_decompress
          - -bin/myisam*
          - -bin/mysqladmin
          - -bin/mysqlbinlog
          - -bin/mysql_client_test
          - -bin/mysql_config*
          - -bin/mysqld_multi
          - -bin/mysqlimport
          - -bin/mysql_install_db
          - -bin/mysql_plugin
          - -bin/mysqlpump
          - -bin/mysql_secure_installation
          - -bin/mysqlshow
          - -bin/mysqlslap
          - -bin/mysql_ssl_rsa_setup
          - -bin/mysqltest
          - -bin/mysql_tzinfo_to_sql
          - -bin/perror
          - -bin/replace
          - -bin/resolveip
          - -bin/resolve_stack_dump
          - -bin/zlib_decompress

      mysql-customizations:
        plugin: copy
        files:
          src/mysql/start_mysql: bin/
          src/mysql/my.cnf: my.cnf
          src/mysql/mysql.server: support-files/
          src/mysql/utilities/*: utilities/
          src/pentaho/h2/*: lib/
          src/pentaho/hsql/*: lib/
          src/pentaho/mysql/mysql-connector-java-5.1.44-bin.jar: lib/
          src/pentaho/mysql/create_quartz_mysql.sql: support-files/
          src/pentaho/config/context.xml: webapps/pentaho/META-INF/
          src/pentaho/config/hibernate-settings.xml: pentaho-solutions/system/hibernate/
          src/pentaho/config/mysql5.hibernate.cfg.xml: pentaho-solutions/system/hibernate/
          src/pentaho/config/quartz.properties: pentaho-solutions/system/quartz/
          src/pentaho/config/repository.xml: pentaho-solutions/system/jackrabbit/
        after: [pentaho]

